### ISSUE TITLE
Crash with from_data()

### ISSUE THREAD

**Issue by Cyrus-Harding** [zcaliptium/gdinv#14]
This line crashes Godot. 

`for i in range (0, stacks_data):`

`i` becomes a boolean value and can't be iterated upon.

Changing the function to this fixes the issue.
(Notice the added `new_stack.stackSize = stacks_data[i].stackSize`)

```gdscript
func from_data(json_data: Dictionary) -> void:
	var stacks_data = json_data.get("stacks", []);
	
	clear();
	
	if (typeof(stacks_data) == TYPE_ARRAY):
		# For finite inventory.
		if (RestrictStackSize):
			for i in range (0, stacks_data.size()):
				if (i >= STACKS.size()):
					break;

				# Skip invalid stacks (null elements in array).
				if (stacks_data[i] == null):
					continue;

				var new_stack = GDInv_ItemStack.new();
				new_stack.from_data(stacks_data[i]);
				STACKS[i] = new_stack;
		else:
			for i in range (0, stacks_data.size()):
				print(stacks_data[i])
				var new_stack = GDInv_ItemStack.new();
				new_stack.from_data(stacks_data[i]);
				new_stack.stackSize = stacks_data[i].stackSize
				print(new_stack.stackSize)
				STACKS.append(new_stack);
```

**Comment by Cyrus-Harding** [comment]
I also remember having to remove a type-specifier from a line because it crashed the game on launch. I can't remember what line it was. I think it was a variable that was defined as an array, but the script forced a dictionary upon it.

**Comment by zcaliptium** [comment]
Why ``new_stack.stackSize = stacks_data[i].stackSize`` was added?

The ``GDInv_ItemStack.from_data`` should do that. Isn't it?
https://github.com/zcaliptium/gdinv/blob/8a08eeaf3a1509496534cbd3ff2a59a64bc49c62/GDInv_ItemStack.gd#L25-L37

**Comment by zcaliptium** [comment]
Okay... That could be ``TYPE_INT`` sometimes. In case if you do ``to_data`` and then ``from_data`` without converting it into JSON.

Created new issue ticket for that. #16
