### ISSUE TITLE
ObjectDB instances leaked at exit

### ISSUE THREAD

**Issue by LazarNajdenov** [zcaliptium/gdinv#17]
After setting up everything following the [Wiki](https://github.com/zcaliptium/gdinv/wiki), I added one `.json` file representing an item, which is successfully loaded through the Singleton `GDInv_ItemDB`, and everything seemed fine. However, upon closing the game, I stumbled across the console logging out that some `Object` instances were leaked. 

Therefore, I run again with `--verbose` flag (in case you wonder how, from the editor go to `Project settings` => `editor` => `run args` and put `--verbose` in there). Here I show you an example of the output with the leaked instance:
  
![image](https://user-images.githubusercontent.com/45427151/160867604-658d5dc4-9035-4e37-b39c-865160b519ae.png)

As you can see, the `GDInv_ItemDefinition` class was leaked. Hence, I checked out in the codebase where it was generated, and found out that in the Singleton class `GDInv_ItemDB` inside the `load_item` function, a `GDInv_ItemDefinition` instance is created, which is a class that extends `Object`, which however is not freed when the game is closed, leading to the warning above.

So I just changed it to extend a `Reference`, which will be freed automatically when the game closes leading to no leaks, but I'm not sure whether this is right solution or not. Any thoughts?

It might even be that I have made a mistake along the way, and this is not supposed to happen usually. In case you think this is the reality, please let me know, thank you.

**Comment by zcaliptium** [comment]
Hmmm... I never care about memory management in case if the game will be closed. Anyway operating system should free all the memory allocated per game process.

**Comment by LazarNajdenov** [comment]
Understood, I guess I will close the issue then. Thanks for the reply.
