### ISSUE TITLE
maxStackSize exceeded causes an item to just be added to a different slot. Is this intended?

### ISSUE THREAD

**Issue by jay-jlm** [zcaliptium/gdinv#2]
Maybe I just don't correctly understand how slots and stacks should work.
I would expect that by setting `maxStack: 1` I would be configuring the inventory to only accept 1 item of that type (identifier) and refuse to add beyond that amount.
However the way it currently works, it just "spills over" the new item to a new slot.
This appears somewhat counterintuitive to me.
Let me know what I am getting wrong.

**Comment by zcaliptium** [comment]
You meant ``maxStackSize``? It only limits amount of items in a stack.

Basically the system works mostly in same way as in Minecraft game.
Each slot contains stack. Let's say you have inventory with 4 slots i.e. you can have four stacks.

Then you make arrow item:
```json
{
    "id": "arrow",
    "attributes": {
        "maxStackSize": 16
    }
}
```
So you can carry ``four`` stacks of arrows, each stack/slot contains ``16`` of them. I.e. ``64`` arrows in total.

When you make item like this:
```json
{
    "id": "diamond_sword",
    "attributes": {
        "maxStackSize": 1
    }
}
```

Then it means you can carry ``four`` stacks of swords, but each stack/slot contains only ``1`` sword. I.e. you can carry ``4`` of them in total.

There is no option to limit amount of stacks or total items with specified ``id`` in entire inventory. I didn't add such functionality to make system generic as possible.
