### ISSUE TITLE
Wrong installing

### ISSUE THREAD

**Issue by stalker57241** [zcaliptium/gdinv#7]
I'm thinking github project must repeat structure of "addons" directory("addons/gdinv"). It wrong installing by it...

**Comment by zcaliptium** [comment]
I think the current way IS NOT WRONG!

Godot community just promote incorrect way of organizing project structure. I think it is really bad that every plugin should have all stuff nested inside of ``addons/<plugin_name/>`` directory.

# Explanation
Imagine situation when you want to use **Git** as version control for game developing. And if you want to have plugin added as ``git submodule``. Submodule is easy way to be able simply update the plugin without need to manually download and install plugin files.

If you want to put ``gdinv`` as submodule then can make ``.gitmodules`` with such configuration:
```
[submodule "addons/gdinv"]
	path = addons/gdinv
	url = git@github.com:zcaliptium/gdinv.git
```
## How it works in my way
``gdinv`` will be installed into  ``addons/gdinv``...

## Wrong way you suggested
But if I will nest plugin contents ``addons/gdinv`` at ``gdinv`` resository then it will be ridiculously stupid...

You will have something like:
``addons/gdinv/addons/gdinv``

**Comment by stalker57241** [comment]
Well, I see what you mean. This is a very interesting option that I didn't think about when I asked the question. Thanks
