### ISSUE TITLE
Inventory should extend Node

### ISSUE THREAD

**Issue by rawsp33d** [zcaliptium/gdinv#9]
I think `GDInv_Inventory` needs to extend `Node`, because otherwise it can't work with static typing as all the `get_node` kind of functions expect `Node`s.

For example all of these give errors:

```gdscript
onready var inventory: GDInv_Inventory = $inventory
onready var inventory: GDInv_Inventory = $inventory as GDInv_Inventory
onready var inventory := $inventory as GDInv_Inventory

_ready():
  var inv: GDInv_Inventory = $inventory
```

I believe this is because `GDInv_Inventory` extends `Object` and not `Node`.

**Comment by rawsp33d** [comment]
I came up with a weird workaround for now that tricks the type system's shallow resolution.

```gdscript
onready var inventoryNode = $inventory # this is very explicitly untyped, to make this work
onready var inventory: GDInv_Inventory = inventoryNode
```

It's much better for me than leaving the inventory variable itself untyped, but I do still think inventory should extend Node to prevent workarounds like these. You're not really supposed to add non-Nodes to the scene tree, and doing so is making Godot freak out. Your use of `add_custom_type` says Inventory is a Node which "makes this work" but it's all built on a lie :sweat_smile:

**Comment by zcaliptium** [comment]
@rosshadden Hello! Sorry, my bad. )
